#!/usr/bin/env python

import argparse
from cmlkit.autotune.core import run_autotune
import cmlkit.inout as cmlio

parser = argparse.ArgumentParser(description='Start an autotune run.')
parser.add_argument('infile', metavar='infile', type=str,
                    help='path to a yaml autotune input file')

args = parser.parse_args()

r = cmlio.read_yaml(args.infile)

run_autotune(r)
